# Generated by Django 2.1.1 on 2018-09-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentalname', models.CharField(max_length=128, unique='true')),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateField(auto_now_add=True)),
                ('cost', models.IntegerField(default=0)),
                ('refcar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.Car')),
            ],
        ),
    ]
