# Generated by Django 2.1.1 on 2018-09-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rentals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rentalname',
        ),
    ]
