# Generated by Django 2.1.1 on 2018-09-07 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_auto_20180906_1217'),
        ('Rentals', '0002_remove_rental_rentalname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='refcar',
        ),
        migrations.AddField(
            model_name='rental',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='Cars.Car'),
            preserve_default=False,
        ),
    ]
