# Generated by Django 2.1.1 on 2018-09-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('year',)},
        ),
        migrations.RemoveField(
            model_name='car',
            name='carname',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
